version: "3.8"

services:
  node-app:
    container_name: node-app-container # Custom container name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Maps port 8000 on the host to port 8000 in the container
    environment:
      NODE_ENV: production
    restart: always # Ensures the container restarts automatically on failure
